IF OBJECT_ID('dbo.STAGING_TRANSACTIONS', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.STAGING_TRANSACTIONS;
END;
GO

CREATE TABLE dbo.STAGING_TRANSACTIONS
(
    TransactionId BIGINT NOT NULL,
    AccountingDate DATE NOT NULL,
    AccountNumber VARCHAR(20) NOT NULL,
    Amount DECIMAL(18, 2) NOT NULL,
    Description VARCHAR(200) NULL,
    IsValid BIT NOT NULL,

    CONSTRAINT PK_STAGING_TRANSACTIONS
        PRIMARY KEY (TransactionId)
);
GO